/*
 * JSP generated by Resin Professional 4.0.48 (built Wed, 17 Feb 2016 11:03:24 PST)
 */

package _jsp._dyconfig._phoneinfo;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.godoing.rose.http.common.*;

public class _addimei__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=gb2312");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    out.print((request.getContextPath()));
    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((request.getContextPath()));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((request.getContextPath()));
    out.write(_jsp_string3, 0, _jsp_string3.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -8002497470487589159L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("dyconfig/phoneInfo/addImei.jsp"), -58318410373908324L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "bean", "/WEB-INF/struts-bean");
      manager.addTaglibFunctions(_jsp_functionMap, "logic", "/WEB-INF/struts-logic");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string2;
  private final static char []_jsp_string3;
  private final static char []_jsp_string1;
  private final static char []_jsp_string0;
  static {
    _jsp_string2 = "/public/public.js\"></script>   <!-- \u8c03\u7528\u6b64\u65b9\u6cd5 -->\r\n		<script language=\"JavaScript\"\r\n			src=\"".toCharArray();
    _jsp_string3 = "/public/My97DatePicker/WdatePicker.js\"></script>\r\n	</head>\r\n\r\n	<body>\r\n		<span class=\"title_1\"></span>\r\n<form name=\"frm\" method=\"post\" action=\"doPhoneInfo.do?method=addImei\" onsubmit=\"return onAdd()\">\r\n  <p>\u8bf7\u9009\u62e9\u5f55\u5165\u7c7b\u578b:</p>\r\n  	<input type=\"radio\" name=\"addType\" value=\"0\" checked=\"checked\"/>\u624b\u52a8\u5f55\u5165\r\n  	<input type=\"radio\" name=\"addType\" value=\"1\" hidden=\"hidden\" title=\"excel\u5f55\u5165\"/>\r\n  	<input type=\"radio\" name=\"addType\" value=\"2\"/>\u6587\u672c\u5f55\u5165 \r\n  	<br/><br/>\r\n    <input type=\"button\" name=\"back\"accesskey=\"b\" tabindex=\"b\" value=\"\u8fd4 \u56de\" class=\"but_1\" onclick=\"location='doPhoneInfo.do?method=queryPhoneInfo'\"  style=\"font-size:12;width:50px;height:21px;\">\r\n	<input type=\"submit\" name=\"ok\"accesskey=\"y\" tabindex=\"y\"  value=\"\u4e0b\u4e00\u6b65\" class=\"but_1\" style=\"font-size:12;width:50px;height:21px;\" >\r\n</form>\r\n	</body>\r\n</html>".toCharArray();
    _jsp_string1 = "/css/tbls.css\"\r\n			rel=\"stylesheet\" type=\"text/css\">\r\n		<script language=\"JavaScript\"\r\n			src=\"".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n<html>\r\n	<head>\r\n		<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n		<title>\u65e0\u6807\u9898\u6587\u6863</title>\r\n		<link href=\"".toCharArray();
  }
}
