/*
 * JSP generated by Resin Professional 4.0.48 (built Wed, 17 Feb 2016 11:03:24 PST)
 */

package _jsp._dyconfig._phoneinfo;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.godoing.rose.http.common.*;

public class _manualinputimei__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = new TagState();

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_state.release();
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=gb2312");
    org.apache.struts.taglib.logic.IterateTag _jsp_IterateTag_0 = null;
    org.apache.struts.taglib.bean.WriteTag _jsp_WriteTag_1 = null;

    out.write(_jsp_string0, 0, _jsp_string0.length);
    out.print((request.getContextPath()));
    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((request.getContextPath()));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((request.getContextPath()));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    com.caucho.jsp.BodyContentImpl _jsp_endTagHack2 = null;
    _jsp_IterateTag_0 = _jsp_state.get_jsp_IterateTag_0(pageContext, _jsp_parent_tag);
    int _jspEval4 = _jsp_IterateTag_0.doStartTag();
    if (_jspEval4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out = pageContext.pushBody();
      _jsp_endTagHack2 = (com.caucho.jsp.BodyContentImpl) out;
      _jsp_IterateTag_0.setBodyContent(_jsp_endTagHack2);
      do {
        out.write(_jsp_string4, 0, _jsp_string4.length);
        _jsp_WriteTag_1 = _jsp_state.get_jsp_WriteTag_1(pageContext, _jsp_parent_tag);
        _jsp_WriteTag_1.setProperty("id");
        _jsp_WriteTag_1.doStartTag();
        out.write(_jsp_string5, 0, _jsp_string5.length);
        _jsp_WriteTag_1.setProperty("project_name");
        _jsp_WriteTag_1.doStartTag();
        out.write(_jsp_string6, 0, _jsp_string6.length);
      } while (_jsp_IterateTag_0.doAfterBody() == javax.servlet.jsp.tagext.IterationTag.EVAL_BODY_AGAIN);
      out = pageContext.popBody();
    }
    _jsp_IterateTag_0.doEndTag();
    if (_jsp_endTagHack2 != null) {
      pageContext.releaseBody(_jsp_endTagHack2);
      _jsp_endTagHack2 = null;
    }
    out.write(_jsp_string7, 0, _jsp_string7.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -8002497470487589159L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("dyconfig/phoneInfo/manualInputImei.jsp"), -7723178926774980969L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/tld/struts-logic.tld"), 8151595965222989444L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/tld/struts-bean.tld"), -6431408965588936799L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.struts.taglib.bean.WriteTag", 8911154127381070432L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.struts.taglib.logic.IterateTag", -9049918858482870556L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.struts.taglib.logic.IterateTei", -5937946434527624669L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }

  final static class TagState {
    private org.apache.struts.taglib.logic.IterateTag _jsp_IterateTag_0;

    final org.apache.struts.taglib.logic.IterateTag get_jsp_IterateTag_0(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_IterateTag_0 == null) {
        _jsp_IterateTag_0 = new org.apache.struts.taglib.logic.IterateTag();
        _jsp_IterateTag_0.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_IterateTag_0.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_IterateTag_0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_IterateTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_IterateTag_0.setName("list");
        _jsp_IterateTag_0.setId("element");
      }

      return _jsp_IterateTag_0;
    }
    private org.apache.struts.taglib.bean.WriteTag _jsp_WriteTag_1;

    final org.apache.struts.taglib.bean.WriteTag get_jsp_WriteTag_1(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_WriteTag_1 == null) {
        _jsp_WriteTag_1 = new org.apache.struts.taglib.bean.WriteTag();
        _jsp_WriteTag_1.setPageContext(pageContext);
        _jsp_WriteTag_1.setParent((javax.servlet.jsp.tagext.Tag) _jsp_IterateTag_0);
        _jsp_WriteTag_1.setName("element");
      }

      return _jsp_WriteTag_1;
    }

    void release()
    {
      if (_jsp_IterateTag_0 != null) {
        _jsp_IterateTag_0.release();
        _jsp_IterateTag_0 = null;
      }
      if (_jsp_WriteTag_1 != null) {
        _jsp_WriteTag_1.release();
        _jsp_WriteTag_1 = null;
      }
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "bean", "/WEB-INF/struts-bean");
      manager.addTaglibFunctions(_jsp_functionMap, "logic", "/WEB-INF/struts-logic");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string6;
  private final static char []_jsp_string3;
  private final static char []_jsp_string2;
  private final static char []_jsp_string4;
  private final static char []_jsp_string5;
  private final static char []_jsp_string1;
  private final static char []_jsp_string7;
  private final static char []_jsp_string0;
  static {
    _jsp_string6 = "\r\n  				".toCharArray();
    _jsp_string3 = "/public/My97DatePicker/WdatePicker.js\"></script>\r\n	</head>\r\n	<script type=\"text/javascript\">\r\n		function add(){\r\n		    if(frmGo.belongProject.value == \"\"){\r\n			   alert(\"\u8bf7\u9009\u62e9\u9879\u76ee\");\r\n			   return false;\r\n			}\r\n			if(frmGo.serieNo.value.trim() == \"\"){\r\n				alert(\"IMEI\u53f7\u4e0d\u80fd\u4e3a\u7a7a\");\r\n				frmGo.serieNo.focus();\r\n				return false;\r\n			}else{\r\n				var no = frmGo.serieNo.value;\r\n				var reg = /^\\d{15}$/;\r\n				if(!reg.test(no)){\r\n					alert(\"IMEI\u53f7\u683c\u5f0f\u4e0d\u6b63\u786e\");\r\n					frmGo.serieNo.focus();\r\n					return false;\r\n				}\r\n			}		\r\n			if(frmGo.countNum.value > 100){\r\n			    alert(\"\u624b\u52a8\u8f93\u5165\u7684\u6700\u5927\u503c\u4e3a100\");\r\n			    return false;\r\n			}			\r\n			if(frmGo.countNum.value <= 0){	\r\n			    alert(\"\u624b\u52a8\u8f93\u5165\u7684\u6700\u5c0f\u503c\u4e3a1\");\r\n			    return false;\r\n			}		\r\n				\r\n			frmGo.submit();\r\n		}\r\n	</script>\r\n	<body>\r\n		<br><span class=\"title_1\"></span>\r\n<form name=\"frmGo\" method=\"post\" action=\"doPhoneInfo.do?method=manualInput\" onsubmit=\"return onAdd()\">\r\n  	<table>\r\n  		<tr>\r\n  			<td>\u9879\u76ee:</td>\r\n  			<td>\r\n  				".toCharArray();
    _jsp_string2 = "/public/public.js\"></script>   <!-- \u8c03\u7528\u6b64\u65b9\u6cd5 -->\r\n		<script language=\"JavaScript\"\r\n			src=\"".toCharArray();
    _jsp_string4 = "\r\n  					<input type=\"radio\" name=\"belongProject\" value=\"".toCharArray();
    _jsp_string5 = "\"/>\r\n  					".toCharArray();
    _jsp_string1 = "/css/tbls.css\"\r\n			rel=\"stylesheet\" type=\"text/css\">\r\n		<script language=\"JavaScript\"\r\n			src=\"".toCharArray();
    _jsp_string7 = "\r\n  			</td>\r\n  		</tr>\r\n  		<tr>\r\n  			<td>\u6700\u5c0fIMEI:</td>\r\n  			<td><input type=\"text\" name=\"serieNo\" id=\"serieNo\"/></td>\r\n  		</tr>\r\n  		<tr>\r\n  			<td>\u6570\u91cf:</td>\r\n  			<td><input type=\"text\" name=\"countNum\" id=\"countNum\"/></td>\r\n  		</tr>\r\n  		<tr></tr>\r\n  	</table>\r\n  	\r\n    <input type=\"button\" name=\"back\"accesskey=\"b\" tabindex=\"b\" value=\"\u8fd4 \u56de\" class=\"but_1\" onclick=\"location='doPhoneInfo.do?method=initInsert'\"  style=\"font-size:12;width:50px;height:21px;\">\r\n	<input type=\"button\" name=\"ok\"accesskey=\"y\" tabindex=\"y\"  value=\"\u786e\u8ba4\" class=\"but_1\" onclick=\"add()\" style=\"font-size:12;width:50px;height:21px;\" >\r\n</form>\r\n	</body>\r\n</html>".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n<html>\r\n	<head>\r\n		<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n		<title>\u65e0\u6807\u9898\u6587\u6863</title>\r\n		<link href=\"".toCharArray();
  }
}
