/*
 * JSP generated by Resin Professional 4.0.48 (built Wed, 17 Feb 2016 11:03:24 PST)
 */

package _jsp._sysadmin._userinfo;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.godoing.rose.http.common.*;
import com.godoing.rose.lang.*;

public class _userupdate__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = null;

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=gb2312");

    out.write(_jsp_string0, 0, _jsp_string0.length);
    com.godoing.rose.lang.DataMap userInfo;
    userInfo = (com.godoing.rose.lang.DataMap) pageContext.getRequest().getAttribute("userInfo");
    if (userInfo == null) {
      userInfo = new com.godoing.rose.lang.DataMap();
      pageContext.getRequest().setAttribute("userInfo", userInfo);
    }
    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((request.getContextPath()));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((request.getContextPath()));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((userInfo.getAt("id")));
    out.write(_jsp_string4, 0, _jsp_string4.length);
    out.print((userInfo.getAt("userCode")));
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((userInfo.getAt("userName")));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((userInfo.getAt("userCode") ));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    out.print((userInfo.getAt("userCode") ));
    out.write(_jsp_string8, 0, _jsp_string8.length);
    out.print((userInfo.getAt("passWrd1")));
    out.write(_jsp_string9, 0, _jsp_string9.length);
    if(!userInfo.getAt("userCode").equals("admin")){ 
    out.write(_jsp_string10, 0, _jsp_string10.length);
    if("1".equals("" + userInfo.getAt("tag"))){
    out.write(_jsp_string11, 0, _jsp_string11.length);
    }
    out.write(_jsp_string12, 0, _jsp_string12.length);
    if("0".equals("" + userInfo.getAt("tag"))){
    out.write(_jsp_string11, 0, _jsp_string11.length);
    }
    out.write(_jsp_string13, 0, _jsp_string13.length);
    } 
    out.write(_jsp_string14, 0, _jsp_string14.length);
    out.print((userInfo.getAt("remark")));
    out.write(_jsp_string15, 0, _jsp_string15.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -8002497470487589159L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysAdmin/userInfo/userUpdate.jsp"), -3048842649042216419L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
  }

  final static class TagState {

    void release()
    {
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string5;
  private final static char []_jsp_string2;
  private final static char []_jsp_string14;
  private final static char []_jsp_string4;
  private final static char []_jsp_string15;
  private final static char []_jsp_string7;
  private final static char []_jsp_string3;
  private final static char []_jsp_string12;
  private final static char []_jsp_string0;
  private final static char []_jsp_string8;
  private final static char []_jsp_string9;
  private final static char []_jsp_string1;
  private final static char []_jsp_string11;
  private final static char []_jsp_string6;
  private final static char []_jsp_string13;
  private final static char []_jsp_string10;
  static {
    _jsp_string5 = "\" />\r\n<input name=\"userName\" type=\"hidden\" value=\"".toCharArray();
    _jsp_string2 = "/css/tbls.css\" rel=\"stylesheet\" type=\"text/css\">\r\n<script language=\"JavaScript\" src=\"".toCharArray();
    _jsp_string14 = "\r\n  <!-- \r\n  <tr class=\"tr_11\">\r\n    <td width=\"7%\" align=\"right\">\u6e20\u9053\u67e5\u770b\u6743\u9650&nbsp;</td>\r\n    <td ><div align=\"left\">\r\n      <input name=\"channelPower\" type=\"button\"  accesskey=\"p\" tabindex=\"p\" class=\"but_1\" onclick=\"onChannelPower()\" value=\"\u914d\u7f6e\">\r\n    </div></td>\r\n    </tr>\r\n     -->\r\n  <tr class=\"tr_11\">\r\n    <td width=\"7%\" align=\"left\">&nbsp;&nbsp;\u5907\u6ce8</td>\r\n    <td align=\"left\" >\r\n      <textarea name=\"remark\" id=\"remark\" rows=\"5\" cols=\"50\" class=\"txt_1\">".toCharArray();
    _jsp_string4 = "\" >\r\n<input name=\"userCode\" type=\"hidden\" value=\"".toCharArray();
    _jsp_string15 = "</textarea>\r\n    </td>\r\n    <td><font color=\"red\">\uff08\u5b57\u6570\u4e0d\u80fd\u8d85\u8fc730\u5b57\uff09</font></td>\r\n  </tr>\r\n  <tr  class=\"tr_11\">\r\n    <td></td>\r\n    <td  align=\"left\">&nbsp;&nbsp;&nbsp;<input type=\"button\" name=\"ok\" accesskey=\"y\" tabindex=\"y\"  value=\"\u786e \u5b9a\" class=\"but_1\" onclick=\"onUpdate()\">\r\n	\r\n      <input type=\"button\" name=\"back\" accesskey=\"b\" tabindex=\"b\" value=\"\u8fd4 \u56de\" class=\"but_1\" onclick=\"location='doUserInfo.do?method=queryUserInfo'\">\r\n    </td>\r\n  </tr>\r\n</table>\r\n</form>\r\n</body>\r\n</html>\r\n".toCharArray();
    _jsp_string7 = "</font>\r\n     </th>\r\n   </tr>\r\n   <!-- <tr class=\"tr_11\">\r\n   	<td>&nbsp;&nbsp;\u767b\u5f55\u8d26\u53f7</td>\r\n   	<td>".toCharArray();
    _jsp_string3 = "/public/public.js\"></script>\r\n<title>\u65e0\u6807\u9898\u6587\u6863</title>\r\n</head>\r\n<script language=\"javascript\">\r\nfunction onUpdate(){\r\n	if(frm.passWrd.value.trim() == ''){\r\n		alert(\"\u5bc6\u7801\u4e0d\u80fd\u4e3a\u7a7a\");\r\n		frm.passWrd.focus();\r\n		return false;\r\n	}else{\r\n		var passWrd = frm.passWrd.value;\r\n		var reg = /^\\w{5,15}$/;		\r\n		if(!reg.test(passWrd)){\r\n			alert(\"\u5bc6\u7801\u683c\u5f0f\u4e0d\u6b63\u786e\uff0c\u8bf7\u91cd\u65b0\u8f93\u5165\uff01\");\r\n			frm.passWrd.focus();\r\n			return false;\r\n		}\r\n	}\r\n	if(frm.remark.value.trim().length > 30){\r\n		alert(\"\u5b57\u6570\u4e0d\u80fd\u8d85\u8fc730\u5b57\");\r\n		frm.remark.focus();\r\n		return false;\r\n	}\r\n	frm.submit();\r\n}\r\nfunction onChannelPower() {\r\nvar id = frm.id.value.trim();\r\nvar userCode = frm.userCode.value.trim();\r\nwindow.location=\"doUserInfo.do?method=initChannelPower&id=\"+id+\"&userCode=\"+userCode+\"\";\r\n}\r\nfunction onAdverPower() {\r\nvar id = frm.id.value.trim();\r\nvar userCode = frm.userCode.value.trim();\r\nwindow.location=\"doUserInfo.do?method=initAdverPower&id=\"+id+\"&userCode=\"+userCode+\"\";\r\n}\r\n\r\n</script>\r\n<body>\r\n<span class=\"title_1\"></span>\r\n<form name=\"frm\" method=\"post\" action=\"doUserInfo.do?method=updateUserInfo\" onsubmit=\"return onUpdate()\">\r\n<input name=\"id\" type=\"hidden\" value=\"".toCharArray();
    _jsp_string12 = ">\r\n	          \u5426<input type=\"radio\" name=\"tag\" class=\"radio_1\" value=\"0\" ".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string8 = "</td>\r\n   </tr> -->\r\n   <tr class=\"tr_11\">\r\n    <td width=\"7%\" align=\"left\">&nbsp;&nbsp;\u5bc6\u7801</td>\r\n    <td align=\"left\" width=\"20%\">\r\n    	<input name=\"passWrd\" type=\"text\"  accesskey=\"p\" tabindex=\"p\" value=\"".toCharArray();
    _jsp_string9 = "\">\r\n	  	<font color=\"red\">*\uff085~15\u4f4d\u5b57\u6bcd\u3001\u6570\u5b57\u6216\u4e0b\u6ed1\u7ebf\u7ec4\u5408\uff09</font>\r\n    </td>\r\n  </tr>\r\n  ".toCharArray();
    _jsp_string1 = "\r\n\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n<link href=\"".toCharArray();
    _jsp_string11 = "checked".toCharArray();
    _jsp_string6 = "\" />\r\n<table width=\"100%\" border=\"0\"cellpadding=\"0\" cellspacing=\"1\"  class=\"tbl_11\">\r\n  <tr>\r\n     <th colspan=\"3\" nowrap=\"nowrap\" align=\"left\">\r\n                           \u7cfb\u7edf\u7528\u6237\u914d\u7f6e-<font color=\"#FFFF00\">".toCharArray();
    _jsp_string13 = ">\r\n    </td>\r\n  </tr>\r\n  ".toCharArray();
    _jsp_string10 = "\r\n  <tr class=\"tr_11\">\r\n    <td width=\"7%\" align=\"left\">&nbsp;&nbsp;\u662f\u5426\u751f\u6548 </td>\r\n    <td align=\"left\">\r\n    	\u662f<input name=\"tag\" type=\"radio\" class=\"radio_1\" value=\"1\" ".toCharArray();
  }
}
