/*
 * JSP generated by Resin Professional 4.0.48 (built Wed, 17 Feb 2016 11:03:24 PST)
 */

package _jsp._sysadmin._userinfo;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.godoing.rose.http.common.*;
import com.wtwd.common.lang.*;
import com.wtwd.common.config.Config;
import com.wtwd.app.LoginUser;

public class _usermain__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = new TagState();

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_state.release();
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=gb2312");
    org.apache.struts.taglib.logic.IterateTag _jsp_IterateTag_0 = null;
    org.apache.struts.taglib.bean.DefineTag _jsp_DefineTag_1 = null;
    java.lang.String userCode = null;
    java.lang.String groupCode = null;
    org.apache.struts.taglib.bean.WriteTag _jsp_WriteTag_2 = null;
    org.apache.struts.taglib.logic.EqualTag _jsp_EqualTag_3 = null;
    org.apache.struts.taglib.bean.WriteTag _jsp_WriteTag_4 = null;
    org.apache.struts.taglib.logic.EmptyTag _jsp_EmptyTag_5 = null;
    org.apache.struts.taglib.logic.NotEmptyTag _jsp_NotEmptyTag_6 = null;
    org.apache.struts.taglib.bean.WriteTag _jsp_WriteTag_7 = null;
    org.apache.struts.taglib.logic.NotEqualTag _jsp_NotEqualTag_8 = null;
    org.apache.struts.taglib.bean.WriteTag _jsp_WriteTag_9 = null;

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
	/*\u9875\u9762\u5c5e\u6027*/
	PagePys pys = (PagePys) request.getAttribute("PagePys");
	LoginUser loginUser = (LoginUser)request.getSession().getAttribute(Config.SystemConfig.LOGINUSER);
	String role = loginUser.getGroupCode();
	String loginUserCode = loginUser.getUserCode();

    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((request.getContextPath()));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((request.getContextPath()));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    if(!"\u64cd\u4f5c\u5458".equals(role)){ 
    out.write(_jsp_string4, 0, _jsp_string4.length);
    } 
    out.write(_jsp_string5, 0, _jsp_string5.length);
    com.caucho.jsp.BodyContentImpl _jsp_endTagHack10 = null;
    _jsp_IterateTag_0 = _jsp_state.get_jsp_IterateTag_0(pageContext, _jsp_parent_tag);
    int _jspEval12 = _jsp_IterateTag_0.doStartTag();
    if (_jspEval12 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out = pageContext.pushBody();
      _jsp_endTagHack10 = (com.caucho.jsp.BodyContentImpl) out;
      _jsp_IterateTag_0.setBodyContent(_jsp_endTagHack10);
      do {
        java.lang.Object element;
        element = (java.lang.Object)pageContext.findAttribute("element");
        out.write(_jsp_string6, 0, _jsp_string6.length);
        _jsp_DefineTag_1 = _jsp_state.get_jsp_DefineTag_1(pageContext, _jsp_parent_tag);
        _jsp_DefineTag_1.setId("userCode");
        _jsp_DefineTag_1.setProperty("userCode");
        _jsp_DefineTag_1.doEndTag();
        userCode = (java.lang.String)pageContext.findAttribute("userCode");
        out.write(_jsp_string7, 0, _jsp_string7.length);
        _jsp_DefineTag_1.setId("groupCode");
        _jsp_DefineTag_1.setProperty("groupCode");
        _jsp_DefineTag_1.doEndTag();
        groupCode = (java.lang.String)pageContext.findAttribute("groupCode");
        out.write(_jsp_string8, 0, _jsp_string8.length);
        _jsp_WriteTag_2 = _jsp_state.get_jsp_WriteTag_2(pageContext, _jsp_parent_tag);
        _jsp_WriteTag_2.setProperty("userCode");
        _jsp_WriteTag_2.doStartTag();
        out.write(_jsp_string9, 0, _jsp_string9.length);
        _jsp_WriteTag_2.setProperty("groupCode");
        _jsp_WriteTag_2.doStartTag();
        out.write(_jsp_string10, 0, _jsp_string10.length);
        _jsp_WriteTag_2.setProperty("passWrd1");
        _jsp_WriteTag_2.doStartTag();
        out.write(_jsp_string11, 0, _jsp_string11.length);
        _jsp_EqualTag_3 = _jsp_state.get_jsp_EqualTag_3(pageContext, _jsp_parent_tag);
        _jsp_EqualTag_3.setValue("0");
        int _jspEval35 = _jsp_EqualTag_3.doStartTag();
        if (_jspEval35 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write(_jsp_string12, 0, _jsp_string12.length);
        }
        out.write(_jsp_string13, 0, _jsp_string13.length);
        _jsp_EqualTag_3.setValue("1");
        int _jspEval39 = _jsp_EqualTag_3.doStartTag();
        if (_jspEval39 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write(_jsp_string14, 0, _jsp_string14.length);
        }
        out.write(_jsp_string10, 0, _jsp_string10.length);
        _jsp_WriteTag_4 = _jsp_state.get_jsp_WriteTag_4(pageContext, _jsp_parent_tag);
        _jsp_WriteTag_4.setProperty("createDate");
        _jsp_WriteTag_4.doStartTag();
        out.write(_jsp_string10, 0, _jsp_string10.length);
        _jsp_WriteTag_4.setProperty("updateDate");
        _jsp_WriteTag_4.doStartTag();
        out.write(_jsp_string15, 0, _jsp_string15.length);
        _jsp_EmptyTag_5 = _jsp_state.get_jsp_EmptyTag_5(pageContext, _jsp_parent_tag);
        int _jspEval51 = _jsp_EmptyTag_5.doStartTag();
        if (_jspEval51 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write('\u65e0');
        }
        out.write(_jsp_string13, 0, _jsp_string13.length);
        _jsp_NotEmptyTag_6 = _jsp_state.get_jsp_NotEmptyTag_6(pageContext, _jsp_parent_tag);
        int _jspEval55 = _jsp_NotEmptyTag_6.doStartTag();
        if (_jspEval55 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write(_jsp_string16, 0, _jsp_string16.length);
          _jsp_WriteTag_7 = _jsp_state.get_jsp_WriteTag_7(pageContext, _jsp_parent_tag);
          _jsp_WriteTag_7.doStartTag();
          out.write(_jsp_string13, 0, _jsp_string13.length);
        }
        out.write(_jsp_string17, 0, _jsp_string17.length);
        _jsp_WriteTag_2.setProperty("userCode");
        _jsp_WriteTag_2.doStartTag();
        out.write(_jsp_string18, 0, _jsp_string18.length);
        _jsp_NotEqualTag_8 = _jsp_state.get_jsp_NotEqualTag_8(pageContext, _jsp_parent_tag);
        _jsp_NotEqualTag_8.setValue(loginUserCode );
        int _jspEval67 = _jsp_NotEqualTag_8.doStartTag();
        if (_jspEval67 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write(_jsp_string19, 0, _jsp_string19.length);
          _jsp_WriteTag_9 = _jsp_state.get_jsp_WriteTag_9(pageContext, _jsp_parent_tag);
          _jsp_WriteTag_9.doStartTag();
          out.write(_jsp_string20, 0, _jsp_string20.length);
        }
        out.write(_jsp_string21, 0, _jsp_string21.length);
      } while (_jsp_IterateTag_0.doAfterBody() == javax.servlet.jsp.tagext.IterationTag.EVAL_BODY_AGAIN);
      out = pageContext.popBody();
    }
    _jsp_IterateTag_0.doEndTag();
    if (_jsp_endTagHack10 != null) {
      pageContext.releaseBody(_jsp_endTagHack10);
      _jsp_endTagHack10 = null;
    }
    out.write(_jsp_string22, 0, _jsp_string22.length);
    
							pys.printGoPage(response, "frmGo");
						
    out.write(_jsp_string23, 0, _jsp_string23.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -8002497470487589159L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("sysAdmin/userInfo/userMain.jsp"), -4258975993792184260L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/tld/struts-logic.tld"), 8151595965222989444L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/tld/struts-bean.tld"), -6431408965588936799L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.struts.taglib.bean.DefineTag", -2693187036961555992L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.struts.taglib.bean.DefineTei", -2335408729141923743L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.struts.taglib.bean.WriteTag", 8911154127381070432L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.struts.taglib.logic.EqualTag", 3082214088700057277L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.struts.taglib.logic.EmptyTag", 4788555899151591807L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.struts.taglib.logic.NotEmptyTag", -3350013249834941570L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.struts.taglib.logic.NotEqualTag", -3556668590462086363L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.struts.taglib.logic.IterateTag", -9049918858482870556L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.struts.taglib.logic.IterateTei", -5937946434527624669L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }

  final static class TagState {
    private org.apache.struts.taglib.logic.IterateTag _jsp_IterateTag_0;

    final org.apache.struts.taglib.logic.IterateTag get_jsp_IterateTag_0(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_IterateTag_0 == null) {
        _jsp_IterateTag_0 = new org.apache.struts.taglib.logic.IterateTag();
        _jsp_IterateTag_0.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_IterateTag_0.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_IterateTag_0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_IterateTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
        _jsp_IterateTag_0.setId("element");
        _jsp_IterateTag_0.setName("pageList");
      }

      return _jsp_IterateTag_0;
    }
    private org.apache.struts.taglib.bean.DefineTag _jsp_DefineTag_1;

    final org.apache.struts.taglib.bean.DefineTag get_jsp_DefineTag_1(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_DefineTag_1 == null) {
        _jsp_DefineTag_1 = new org.apache.struts.taglib.bean.DefineTag();
        _jsp_DefineTag_1.setPageContext(pageContext);
        _jsp_DefineTag_1.setParent((javax.servlet.jsp.tagext.Tag) _jsp_IterateTag_0);
        _jsp_DefineTag_1.setName("element");
        _jsp_DefineTag_1.setType("java.lang.String");
      }

      return _jsp_DefineTag_1;
    }
    private org.apache.struts.taglib.bean.WriteTag _jsp_WriteTag_2;

    final org.apache.struts.taglib.bean.WriteTag get_jsp_WriteTag_2(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_WriteTag_2 == null) {
        _jsp_WriteTag_2 = new org.apache.struts.taglib.bean.WriteTag();
        _jsp_WriteTag_2.setPageContext(pageContext);
        _jsp_WriteTag_2.setParent((javax.servlet.jsp.tagext.Tag) _jsp_IterateTag_0);
        _jsp_WriteTag_2.setName("element");
      }

      return _jsp_WriteTag_2;
    }
    private org.apache.struts.taglib.logic.EqualTag _jsp_EqualTag_3;

    final org.apache.struts.taglib.logic.EqualTag get_jsp_EqualTag_3(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_EqualTag_3 == null) {
        _jsp_EqualTag_3 = new org.apache.struts.taglib.logic.EqualTag();
        _jsp_EqualTag_3.setPageContext(pageContext);
        _jsp_EqualTag_3.setParent((javax.servlet.jsp.tagext.Tag) _jsp_IterateTag_0);
        _jsp_EqualTag_3.setName("element");
        _jsp_EqualTag_3.setProperty("tag");
      }

      return _jsp_EqualTag_3;
    }
    private org.apache.struts.taglib.bean.WriteTag _jsp_WriteTag_4;

    final org.apache.struts.taglib.bean.WriteTag get_jsp_WriteTag_4(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_WriteTag_4 == null) {
        _jsp_WriteTag_4 = new org.apache.struts.taglib.bean.WriteTag();
        _jsp_WriteTag_4.setPageContext(pageContext);
        _jsp_WriteTag_4.setParent((javax.servlet.jsp.tagext.Tag) _jsp_IterateTag_0);
        _jsp_WriteTag_4.setName("element");
        _jsp_WriteTag_4.setFormat("yyyy-MM-dd HH:mm:ss");
      }

      return _jsp_WriteTag_4;
    }
    private org.apache.struts.taglib.logic.EmptyTag _jsp_EmptyTag_5;

    final org.apache.struts.taglib.logic.EmptyTag get_jsp_EmptyTag_5(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_EmptyTag_5 == null) {
        _jsp_EmptyTag_5 = new org.apache.struts.taglib.logic.EmptyTag();
        _jsp_EmptyTag_5.setPageContext(pageContext);
        _jsp_EmptyTag_5.setParent((javax.servlet.jsp.tagext.Tag) _jsp_IterateTag_0);
        _jsp_EmptyTag_5.setName("element");
        _jsp_EmptyTag_5.setProperty("remark");
      }

      return _jsp_EmptyTag_5;
    }
    private org.apache.struts.taglib.logic.NotEmptyTag _jsp_NotEmptyTag_6;

    final org.apache.struts.taglib.logic.NotEmptyTag get_jsp_NotEmptyTag_6(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_NotEmptyTag_6 == null) {
        _jsp_NotEmptyTag_6 = new org.apache.struts.taglib.logic.NotEmptyTag();
        _jsp_NotEmptyTag_6.setPageContext(pageContext);
        _jsp_NotEmptyTag_6.setParent((javax.servlet.jsp.tagext.Tag) _jsp_IterateTag_0);
        _jsp_NotEmptyTag_6.setName("element");
        _jsp_NotEmptyTag_6.setProperty("remark");
      }

      return _jsp_NotEmptyTag_6;
    }
    private org.apache.struts.taglib.bean.WriteTag _jsp_WriteTag_7;

    final org.apache.struts.taglib.bean.WriteTag get_jsp_WriteTag_7(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_WriteTag_7 == null) {
        _jsp_WriteTag_7 = new org.apache.struts.taglib.bean.WriteTag();
        _jsp_WriteTag_7.setPageContext(pageContext);
        _jsp_WriteTag_7.setParent((javax.servlet.jsp.tagext.Tag) _jsp_NotEmptyTag_6);
        _jsp_WriteTag_7.setName("element");
        _jsp_WriteTag_7.setProperty("remark");
      }

      return _jsp_WriteTag_7;
    }
    private org.apache.struts.taglib.logic.NotEqualTag _jsp_NotEqualTag_8;

    final org.apache.struts.taglib.logic.NotEqualTag get_jsp_NotEqualTag_8(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_NotEqualTag_8 == null) {
        _jsp_NotEqualTag_8 = new org.apache.struts.taglib.logic.NotEqualTag();
        _jsp_NotEqualTag_8.setPageContext(pageContext);
        _jsp_NotEqualTag_8.setParent((javax.servlet.jsp.tagext.Tag) _jsp_IterateTag_0);
        _jsp_NotEqualTag_8.setName("element");
        _jsp_NotEqualTag_8.setProperty("userCode");
      }

      return _jsp_NotEqualTag_8;
    }
    private org.apache.struts.taglib.bean.WriteTag _jsp_WriteTag_9;

    final org.apache.struts.taglib.bean.WriteTag get_jsp_WriteTag_9(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_WriteTag_9 == null) {
        _jsp_WriteTag_9 = new org.apache.struts.taglib.bean.WriteTag();
        _jsp_WriteTag_9.setPageContext(pageContext);
        _jsp_WriteTag_9.setParent((javax.servlet.jsp.tagext.Tag) _jsp_NotEqualTag_8);
        _jsp_WriteTag_9.setName("element");
        _jsp_WriteTag_9.setProperty("userCode");
      }

      return _jsp_WriteTag_9;
    }

    void release()
    {
      if (_jsp_IterateTag_0 != null) {
        _jsp_IterateTag_0.release();
        _jsp_IterateTag_0 = null;
      }
      if (_jsp_DefineTag_1 != null) {
        _jsp_DefineTag_1.release();
        _jsp_DefineTag_1 = null;
      }
      if (_jsp_WriteTag_2 != null) {
        _jsp_WriteTag_2.release();
        _jsp_WriteTag_2 = null;
      }
      if (_jsp_EqualTag_3 != null) {
        _jsp_EqualTag_3.release();
        _jsp_EqualTag_3 = null;
      }
      if (_jsp_WriteTag_4 != null) {
        _jsp_WriteTag_4.release();
        _jsp_WriteTag_4 = null;
      }
      if (_jsp_EmptyTag_5 != null) {
        _jsp_EmptyTag_5.release();
        _jsp_EmptyTag_5 = null;
      }
      if (_jsp_NotEmptyTag_6 != null) {
        _jsp_NotEmptyTag_6.release();
        _jsp_NotEmptyTag_6 = null;
      }
      if (_jsp_WriteTag_7 != null) {
        _jsp_WriteTag_7.release();
        _jsp_WriteTag_7 = null;
      }
      if (_jsp_NotEqualTag_8 != null) {
        _jsp_NotEqualTag_8.release();
        _jsp_NotEqualTag_8 = null;
      }
      if (_jsp_WriteTag_9 != null) {
        _jsp_WriteTag_9.release();
        _jsp_WriteTag_9 = null;
      }
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "bean", "/WEB-INF/struts-bean");
      manager.addTaglibFunctions(_jsp_functionMap, "logic", "/WEB-INF/struts-logic");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string5;
  private final static char []_jsp_string1;
  private final static char []_jsp_string13;
  private final static char []_jsp_string23;
  private final static char []_jsp_string19;
  private final static char []_jsp_string17;
  private final static char []_jsp_string14;
  private final static char []_jsp_string10;
  private final static char []_jsp_string18;
  private final static char []_jsp_string4;
  private final static char []_jsp_string20;
  private final static char []_jsp_string16;
  private final static char []_jsp_string11;
  private final static char []_jsp_string22;
  private final static char []_jsp_string12;
  private final static char []_jsp_string7;
  private final static char []_jsp_string15;
  private final static char []_jsp_string8;
  private final static char []_jsp_string2;
  private final static char []_jsp_string9;
  private final static char []_jsp_string21;
  private final static char []_jsp_string6;
  private final static char []_jsp_string0;
  private final static char []_jsp_string3;
  static {
    _jsp_string5 = "						\r\n                </th>\r\n                </tr>\r\n                  <tr class=\"title_2\">                  \r\n					<td width=\"10%\">\u767b\u5f55\u8d26\u53f7</td>                   \r\n					<td width=\"10%\">\u89d2\u8272\u540d\u79f0</td>					\r\n					<td width=\"10%\">\u767b\u5f55\u5bc6\u7801</td>\r\n					<td width=\"10%\">\u8d26\u6237\u662f\u5426\u751f\u6548</td>\r\n					<td width=\"15%\">\u521b\u5efa\u65f6\u95f4</td>\r\n					<td width=\"15%\">\u6700\u65b0\u4fee\u6539\u65f6\u95f4</td>\r\n					<td width=\"15%\">\u5907\u6ce8</td>\r\n					<td width=\"15%\">\u64cd\u4f5c</td>                 \r\n				</tr>\r\n				".toCharArray();
    _jsp_string1 = "\r\n\r\n<html>\r\n	<head>\r\n		<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n		<title>\u65e0\u6807\u9898\u6587\u6863</title>\r\n		<link href=\"".toCharArray();
    _jsp_string13 = "\r\n							".toCharArray();
    _jsp_string23 = "\r\n					</td>\r\n				</tr>  \r\n			</table>\r\n		</form>\r\n	</body>\r\n</html>\r\n".toCharArray();
    _jsp_string19 = "\r\n								<a href=# onclick=\"del('".toCharArray();
    _jsp_string17 = "							\r\n						</td>\r\n						<td align=\"left\">\r\n							<a href=# onclick=\"update('".toCharArray();
    _jsp_string14 = "<font style=\"color:green;font-size: 20px;\">\u221a</font>".toCharArray();
    _jsp_string10 = "\r\n						</td>\r\n						<td>\r\n							".toCharArray();
    _jsp_string18 = "')\" style=\"color:#0000FF\" > \u3010\u914d\u7f6e\u3011</a>						\r\n							".toCharArray();
    _jsp_string4 = "\r\n                 <input name=\"inset\" type=\"button\" class=\"but_1\" accesskey=\"a\"\r\n							tabindex=\"a\" value=\"\u6dfb \u52a0\" onclick=\"insert()\">	\r\n				 ".toCharArray();
    _jsp_string20 = "')\" style=\"color:#0000FF\" > \u3010\u5220\u9664\u3011</a>\r\n							".toCharArray();
    _jsp_string16 = "\r\n								".toCharArray();
    _jsp_string11 = "\r\n						</td>												\r\n						<td>\r\n							".toCharArray();
    _jsp_string22 = "\r\n\r\n			  	<tr class=\"title_3\">\r\n					<td colspan=\"10\" align=\"left\" >\r\n						".toCharArray();
    _jsp_string12 = "<font style=\"color:red;font-size: 20px;\">\u00d7</font>".toCharArray();
    _jsp_string7 = "\r\n						".toCharArray();
    _jsp_string15 = "\r\n						</td>\r\n						<td align=\"left\">\r\n							".toCharArray();
    _jsp_string8 = "							\r\n						<td>\r\n							".toCharArray();
    _jsp_string2 = "/css/tbls.css\"\r\n			rel=\"stylesheet\" type=\"text/css\">\r\n		<script language=\"JavaScript\"\r\n			src=\"".toCharArray();
    _jsp_string9 = "\r\n						</td>\r\n						<td>						  \r\n						     ".toCharArray();
    _jsp_string21 = "\r\n						</td>\r\n					</tr>\r\n				".toCharArray();
    _jsp_string6 = "\r\n					<tr class=\"tr_5\" onmouseover='this.className=\"tr_4\"' onmouseout='this.className=\"tr_5\"' >\r\n						".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
    _jsp_string3 = "/public/public.js\"></script>   <!-- \u8c03\u7528\u6b64\u65b9\u6cd5 -->\r\n	</head>\r\n	<script language=\"javascript\">\r\nfunction finds(){\r\n	frmGo.submit();\r\n}\r\n\r\nfunction del(userCode){\r\n		if(confirm(\"\u786e\u5b9a\u5220\u9664\u5417?\"))\r\n		{\r\n			frmGo.action = \"doUserInfo.do?method=deleteUserInfo&userCode=\"+userCode+\" \";\r\n			frmGo.submit();\r\n		}\r\n}\r\nfunction insert(){\r\n	frmGo.action = \"doUserInfo.do?method=initInsert\";\r\n	frmGo.submit();\r\n}\r\n\r\n//\u4fee\u6539\u8d26\u6237				\r\nfunction update(userCode)\r\n{\r\n		frmGo.action=\"doUserInfo.do?method=initUpdate&userCode=\"+userCode+\" \";\r\n		frmGo.submit();\r\n	\r\n\r\n}\r\nfunction updateP()\r\n{\r\n	if(countBox()==1){\r\n		frmGo.action=\"doUserInfo.do?method=initUpdatePwd\";\r\n		frmGo.submit();\r\n	}else{alert(\"\u8bf7\u9009\u62e9\u4e00\u884c\u8bb0\u5f55\");}\r\n\r\n}\r\n\r\n\r\n</script>\r\n	<body>\r\n		<span class=\"title_1\"></span>\r\n		<form name=\"frmGo\" method=\"post\"\r\n			action=\"doUserInfo.do?method=queryUserInfo\">\r\n			<table width=\"100%\" class=\"table\" border=0 cellpadding=\"0\" cellspacing=\"1\">\r\n               <tr>\r\n                <th colspan=\"13\" nowrap=\"nowrap\" align=\"left\">\r\n                                                                \u7cfb\u7edf\u7528\u6237\r\n                 ".toCharArray();
  }
}
