/*
 * JSP generated by Resin Professional 4.0.48 (built Wed, 17 Feb 2016 11:03:24 PST)
 */

package _jsp._dyconfig._appuserinfo;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;
import com.godoing.rose.http.common.*;
import com.wtwd.common.lang.*;
import com.wtwd.common.config.Config;
import com.wtwd.app.LoginUser;

public class _appuserinfomain__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  private boolean _caucho_isNotModified;
  private com.caucho.jsp.PageManager _jsp_pageManager;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    com.caucho.jsp.PageContextImpl pageContext = _jsp_pageManager.allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);

    TagState _jsp_state = new TagState();

    try {
      _jspService(request, response, pageContext, _jsp_application, session, _jsp_state);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_state.release();
      _jsp_pageManager.freePageContext(pageContext);
    }
  }
  
  private void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response,
              com.caucho.jsp.PageContextImpl pageContext,
              javax.servlet.ServletContext application,
              javax.servlet.http.HttpSession session,
              TagState _jsp_state)
    throws Throwable
  {
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    javax.servlet.jsp.tagext.JspTag _jsp_parent_tag = null;
    com.caucho.jsp.PageContextImpl _jsp_parentContext = pageContext;
    response.setContentType("text/html;charset=gb2312");
    org.apache.struts.taglib.logic.IterateTag _jsp_IterateTag_0 = null;
    org.apache.struts.taglib.bean.DefineTag _jsp_DefineTag_1 = null;
    java.lang.Integer projectId = null;
    org.apache.struts.taglib.bean.WriteTag _jsp_WriteTag_2 = null;
    org.apache.struts.taglib.bean.WriteTag _jsp_WriteTag_3 = null;
    org.apache.struts.taglib.logic.NotEmptyTag _jsp_NotEmptyTag_4 = null;
    org.apache.struts.taglib.bean.WriteTag _jsp_WriteTag_5 = null;
    org.apache.struts.taglib.logic.EmptyTag _jsp_EmptyTag_6 = null;

    out.write(_jsp_string0, 0, _jsp_string0.length);
    
	/*\u9875\u9762\u5c5e\u6027*/
	PagePys pys = (PagePys) request.getAttribute("PagePys");
	LoginUser loginUser = (LoginUser)request.getSession().getAttribute(Config.SystemConfig.LOGINUSER); 

    out.write(_jsp_string1, 0, _jsp_string1.length);
    out.print((request.getContextPath()));
    out.write(_jsp_string2, 0, _jsp_string2.length);
    out.print((request.getContextPath()));
    out.write(_jsp_string3, 0, _jsp_string3.length);
    out.print((request.getContextPath()));
    out.write(_jsp_string4, 0, _jsp_string4.length);
     if(request.getAttribute("user_id") != null && !request.getAttribute("user_id").equals("")){
    out.write(_jsp_string5, 0, _jsp_string5.length);
    out.print((request.getAttribute("user_id") ));
    out.write(_jsp_string6, 0, _jsp_string6.length);
    out.print((request.getAttribute("user_id") ));
    out.write(_jsp_string7, 0, _jsp_string7.length);
    } 
    out.write(_jsp_string8, 0, _jsp_string8.length);
     if(request.getAttribute("user_id") == null){
    out.write(_jsp_string9, 0, _jsp_string9.length);
    CommUtils.printReqByAtt(request,response,"fNow_date");
    out.write(_jsp_string10, 0, _jsp_string10.length);
    CommUtils.printReqByAtt(request,response,"now_date");
    out.write(_jsp_string11, 0, _jsp_string11.length);
    CommUtils.printReqByAtt(request,response,"user");
    out.write(_jsp_string12, 0, _jsp_string12.length);
    String belongProject = (String)request.getAttribute("belongProject"); 
    out.write(_jsp_string13, 0, _jsp_string13.length);
    com.caucho.jsp.BodyContentImpl _jsp_endTagHack7 = null;
    _jsp_IterateTag_0 = _jsp_state.get_jsp_IterateTag_0(pageContext, _jsp_parent_tag);
    _jsp_IterateTag_0.setId("pro");
    _jsp_IterateTag_0.setName("project");
    int _jspEval9 = _jsp_IterateTag_0.doStartTag();
    if (_jspEval9 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out = pageContext.pushBody();
      _jsp_endTagHack7 = (com.caucho.jsp.BodyContentImpl) out;
      _jsp_IterateTag_0.setBodyContent(_jsp_endTagHack7);
      do {
        java.lang.Object pro;
        pro = (java.lang.Object)pageContext.findAttribute("pro");
        out.write(_jsp_string14, 0, _jsp_string14.length);
        _jsp_DefineTag_1 = _jsp_state.get_jsp_DefineTag_1(pageContext, _jsp_parent_tag);
        _jsp_DefineTag_1.doEndTag();
        projectId = (java.lang.Integer)pageContext.findAttribute("projectId");
        out.write(_jsp_string15, 0, _jsp_string15.length);
        out.print((projectId ));
        out.write(_jsp_string16, 0, _jsp_string16.length);
        out.print((String.valueOf(projectId).equals(belongProject)? "selected" : "" ));
        out.write('>');
        _jsp_WriteTag_2 = _jsp_state.get_jsp_WriteTag_2(pageContext, _jsp_parent_tag);
        _jsp_WriteTag_2.setName("pro");
        _jsp_WriteTag_2.setProperty("project_name");
        _jsp_WriteTag_2.doStartTag();
        out.write(_jsp_string17, 0, _jsp_string17.length);
      } while (_jsp_IterateTag_0.doAfterBody() == javax.servlet.jsp.tagext.IterationTag.EVAL_BODY_AGAIN);
      out = pageContext.popBody();
    }
    _jsp_IterateTag_0.doEndTag();
    if (_jsp_endTagHack7 != null) {
      pageContext.releaseBody(_jsp_endTagHack7);
      _jsp_endTagHack7 = null;
    }
    out.write(_jsp_string18, 0, _jsp_string18.length);
    } 
    out.write(_jsp_string19, 0, _jsp_string19.length);
    com.caucho.jsp.BodyContentImpl _jsp_endTagHack19 = null;
    _jsp_IterateTag_0 = _jsp_state.get_jsp_IterateTag_0(pageContext, _jsp_parent_tag);
    _jsp_IterateTag_0.setId("element");
    _jsp_IterateTag_0.setName("pageList");
    int _jspEval21 = _jsp_IterateTag_0.doStartTag();
    if (_jspEval21 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      out = pageContext.pushBody();
      _jsp_endTagHack19 = (com.caucho.jsp.BodyContentImpl) out;
      _jsp_IterateTag_0.setBodyContent(_jsp_endTagHack19);
      do {
        out.write(_jsp_string20, 0, _jsp_string20.length);
        _jsp_WriteTag_3 = _jsp_state.get_jsp_WriteTag_3(pageContext, _jsp_parent_tag);
        _jsp_WriteTag_3.doStartTag();
        out.write(_jsp_string21, 0, _jsp_string21.length);
        _jsp_WriteTag_2 = _jsp_state.get_jsp_WriteTag_2(pageContext, _jsp_parent_tag);
        _jsp_WriteTag_2.setName("element");
        _jsp_WriteTag_2.setProperty("id");
        _jsp_WriteTag_2.doStartTag();
        out.write(_jsp_string22, 0, _jsp_string22.length);
        _jsp_WriteTag_2.setName("element");
        _jsp_WriteTag_2.setProperty("project");
        _jsp_WriteTag_2.doStartTag();
        out.write(_jsp_string21, 0, _jsp_string21.length);
        _jsp_WriteTag_2.setName("element");
        _jsp_WriteTag_2.setProperty("user_name");
        _jsp_WriteTag_2.doStartTag();
        out.write(_jsp_string21, 0, _jsp_string21.length);
        _jsp_WriteTag_2.setName("element");
        _jsp_WriteTag_2.setProperty("nick_name");
        _jsp_WriteTag_2.doStartTag();
        out.write(_jsp_string23, 0, _jsp_string23.length);
        _jsp_NotEmptyTag_4 = _jsp_state.get_jsp_NotEmptyTag_4(pageContext, _jsp_parent_tag);
        _jsp_NotEmptyTag_4.setProperty("count_device");
        int _jspEval44 = _jsp_NotEmptyTag_4.doStartTag();
        if (_jspEval44 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write(_jsp_string24, 0, _jsp_string24.length);
          _jsp_WriteTag_5 = _jsp_state.get_jsp_WriteTag_5(pageContext, _jsp_parent_tag);
          _jsp_WriteTag_5.setProperty("count_device");
          _jsp_WriteTag_5.doStartTag();
          out.write(_jsp_string25, 0, _jsp_string25.length);
        }
        out.write(_jsp_string25, 0, _jsp_string25.length);
        _jsp_EmptyTag_6 = _jsp_state.get_jsp_EmptyTag_6(pageContext, _jsp_parent_tag);
        _jsp_EmptyTag_6.setProperty("count_device");
        int _jspEval52 = _jsp_EmptyTag_6.doStartTag();
        if (_jspEval52 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write('0');
        }
        out.write(_jsp_string26, 0, _jsp_string26.length);
        _jsp_WriteTag_2.setName("element");
        _jsp_WriteTag_2.setProperty("bind_count");
        _jsp_WriteTag_2.doStartTag();
        out.write(_jsp_string23, 0, _jsp_string23.length);
        _jsp_EmptyTag_6.setProperty("count_share");
        int _jspEval60 = _jsp_EmptyTag_6.doStartTag();
        if (_jspEval60 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write('0');
        }
        out.write(_jsp_string25, 0, _jsp_string25.length);
        _jsp_NotEmptyTag_4.setProperty("count_share");
        int _jspEval64 = _jsp_NotEmptyTag_4.doStartTag();
        if (_jspEval64 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write(_jsp_string24, 0, _jsp_string24.length);
          _jsp_WriteTag_5 = _jsp_state.get_jsp_WriteTag_5(pageContext, _jsp_parent_tag);
          _jsp_WriteTag_5.setProperty("count_share");
          _jsp_WriteTag_5.doStartTag();
          out.write(_jsp_string25, 0, _jsp_string25.length);
        }
        out.write(_jsp_string26, 0, _jsp_string26.length);
        _jsp_WriteTag_2.setName("element");
        _jsp_WriteTag_2.setProperty("password");
        _jsp_WriteTag_2.doStartTag();
        out.write(_jsp_string23, 0, _jsp_string23.length);
        _jsp_EmptyTag_6.setProperty("head");
        int _jspEval76 = _jsp_EmptyTag_6.doStartTag();
        if (_jspEval76 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write('\u65e0');
        }
        out.write(_jsp_string25, 0, _jsp_string25.length);
        _jsp_NotEmptyTag_4.setProperty("head");
        int _jspEval80 = _jsp_NotEmptyTag_4.doStartTag();
        if (_jspEval80 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          out.write(_jsp_string27, 0, _jsp_string27.length);
          _jsp_WriteTag_5 = _jsp_state.get_jsp_WriteTag_5(pageContext, _jsp_parent_tag);
          _jsp_WriteTag_5.setProperty("head");
          _jsp_WriteTag_5.doStartTag();
          out.write(_jsp_string28, 0, _jsp_string28.length);
        }
        out.write(_jsp_string29, 0, _jsp_string29.length);
        _jsp_WriteTag_2.setName("element");
        _jsp_WriteTag_2.setProperty("phone_model");
        _jsp_WriteTag_2.doStartTag();
        out.write(_jsp_string22, 0, _jsp_string22.length);
        _jsp_WriteTag_2.setName("element");
        _jsp_WriteTag_2.setProperty("sys_version");
        _jsp_WriteTag_2.doStartTag();
        out.write(_jsp_string21, 0, _jsp_string21.length);
        _jsp_WriteTag_2.setName("element");
        _jsp_WriteTag_2.setProperty("app_version");
        _jsp_WriteTag_2.doStartTag();
        out.write(_jsp_string30, 0, _jsp_string30.length);
        _jsp_WriteTag_2.setName("element");
        _jsp_WriteTag_2.setProperty("ip");
        _jsp_WriteTag_2.doStartTag();
        out.write(_jsp_string21, 0, _jsp_string21.length);
        _jsp_WriteTag_2.setName("element");
        _jsp_WriteTag_2.setProperty("province");
        _jsp_WriteTag_2.doStartTag();
        out.write(_jsp_string31, 0, _jsp_string31.length);
      } while (_jsp_IterateTag_0.doAfterBody() == javax.servlet.jsp.tagext.IterationTag.EVAL_BODY_AGAIN);
      out = pageContext.popBody();
    }
    _jsp_IterateTag_0.doEndTag();
    if (_jsp_endTagHack19 != null) {
      pageContext.releaseBody(_jsp_endTagHack19);
      _jsp_endTagHack19 = null;
    }
    out.write(_jsp_string32, 0, _jsp_string32.length);
    
							pys.printGoPage(response, "frmGo");
						
    out.write(_jsp_string33, 0, _jsp_string33.length);
  }

  private com.caucho.make.DependencyContainer _caucho_depends
    = new com.caucho.make.DependencyContainer();

  public java.util.ArrayList<com.caucho.vfs.Dependency> _caucho_getDependList()
  {
    return _caucho_depends.getDependencies();
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    _caucho_depends.add(depend);
  }

  protected void _caucho_setNeverModified(boolean isNotModified)
  {
    _caucho_isNotModified = true;
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;

    if (_caucho_isNotModified)
      return false;

    if (com.caucho.server.util.CauchoSystem.getVersionId() != -8002497470487589159L)
      return true;

    return _caucho_depends.isModified();
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
    TagState tagState;
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("dyconfig/appUserInfo/appUserInfoMain.jsp"), 7813852596714640621L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/tld/struts-logic.tld"), 8151595965222989444L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/tld/struts-bean.tld"), -6431408965588936799L, false);
    _caucho_depends.add(depend);
    loader.addDependency(depend);
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.struts.taglib.bean.DefineTag", -2693187036961555992L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.struts.taglib.bean.DefineTei", -2335408729141923743L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.struts.taglib.bean.WriteTag", 8911154127381070432L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.struts.taglib.logic.IterateTag", -9049918858482870556L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.struts.taglib.logic.IterateTei", -5937946434527624669L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.struts.taglib.logic.NotEmptyTag", -3350013249834941570L));
    _caucho_depends.add(new com.caucho.make.ClassDependency("org.apache.struts.taglib.logic.EmptyTag", 4788555899151591807L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }

  final static class TagState {
    private org.apache.struts.taglib.logic.IterateTag _jsp_IterateTag_0;

    final org.apache.struts.taglib.logic.IterateTag get_jsp_IterateTag_0(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_IterateTag_0 == null) {
        _jsp_IterateTag_0 = new org.apache.struts.taglib.logic.IterateTag();
        _jsp_IterateTag_0.setPageContext(pageContext);
        if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.Tag)
          _jsp_IterateTag_0.setParent((javax.servlet.jsp.tagext.Tag) _jsp_parent_tag);
        else if (_jsp_parent_tag instanceof javax.servlet.jsp.tagext.SimpleTag)
          _jsp_IterateTag_0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jsp_parent_tag));
        else
          _jsp_IterateTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      return _jsp_IterateTag_0;
    }
    private org.apache.struts.taglib.bean.DefineTag _jsp_DefineTag_1;

    final org.apache.struts.taglib.bean.DefineTag get_jsp_DefineTag_1(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_DefineTag_1 == null) {
        _jsp_DefineTag_1 = new org.apache.struts.taglib.bean.DefineTag();
        _jsp_DefineTag_1.setPageContext(pageContext);
        _jsp_DefineTag_1.setParent((javax.servlet.jsp.tagext.Tag) _jsp_IterateTag_0);
        _jsp_DefineTag_1.setId("projectId");
        _jsp_DefineTag_1.setName("pro");
        _jsp_DefineTag_1.setProperty("id");
        _jsp_DefineTag_1.setType("java.lang.Integer");
      }

      return _jsp_DefineTag_1;
    }
    private org.apache.struts.taglib.bean.WriteTag _jsp_WriteTag_2;

    final org.apache.struts.taglib.bean.WriteTag get_jsp_WriteTag_2(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_WriteTag_2 == null) {
        _jsp_WriteTag_2 = new org.apache.struts.taglib.bean.WriteTag();
        _jsp_WriteTag_2.setPageContext(pageContext);
        _jsp_WriteTag_2.setParent((javax.servlet.jsp.tagext.Tag) _jsp_IterateTag_0);
      }

      return _jsp_WriteTag_2;
    }
    private org.apache.struts.taglib.bean.WriteTag _jsp_WriteTag_3;

    final org.apache.struts.taglib.bean.WriteTag get_jsp_WriteTag_3(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_WriteTag_3 == null) {
        _jsp_WriteTag_3 = new org.apache.struts.taglib.bean.WriteTag();
        _jsp_WriteTag_3.setPageContext(pageContext);
        _jsp_WriteTag_3.setParent((javax.servlet.jsp.tagext.Tag) _jsp_IterateTag_0);
        _jsp_WriteTag_3.setName("element");
        _jsp_WriteTag_3.setProperty("create_time");
        _jsp_WriteTag_3.setFormat("yyyy-MM-dd HH:mm:ss");
      }

      return _jsp_WriteTag_3;
    }
    private org.apache.struts.taglib.logic.NotEmptyTag _jsp_NotEmptyTag_4;

    final org.apache.struts.taglib.logic.NotEmptyTag get_jsp_NotEmptyTag_4(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_NotEmptyTag_4 == null) {
        _jsp_NotEmptyTag_4 = new org.apache.struts.taglib.logic.NotEmptyTag();
        _jsp_NotEmptyTag_4.setPageContext(pageContext);
        _jsp_NotEmptyTag_4.setParent((javax.servlet.jsp.tagext.Tag) _jsp_IterateTag_0);
        _jsp_NotEmptyTag_4.setName("element");
      }

      return _jsp_NotEmptyTag_4;
    }
    private org.apache.struts.taglib.bean.WriteTag _jsp_WriteTag_5;

    final org.apache.struts.taglib.bean.WriteTag get_jsp_WriteTag_5(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_WriteTag_5 == null) {
        _jsp_WriteTag_5 = new org.apache.struts.taglib.bean.WriteTag();
        _jsp_WriteTag_5.setPageContext(pageContext);
        _jsp_WriteTag_5.setParent((javax.servlet.jsp.tagext.Tag) _jsp_NotEmptyTag_4);
        _jsp_WriteTag_5.setName("element");
      }

      return _jsp_WriteTag_5;
    }
    private org.apache.struts.taglib.logic.EmptyTag _jsp_EmptyTag_6;

    final org.apache.struts.taglib.logic.EmptyTag get_jsp_EmptyTag_6(PageContext pageContext, javax.servlet.jsp.tagext.JspTag _jsp_parent_tag) throws Throwable
    {
      if (_jsp_EmptyTag_6 == null) {
        _jsp_EmptyTag_6 = new org.apache.struts.taglib.logic.EmptyTag();
        _jsp_EmptyTag_6.setPageContext(pageContext);
        _jsp_EmptyTag_6.setParent((javax.servlet.jsp.tagext.Tag) _jsp_IterateTag_0);
        _jsp_EmptyTag_6.setName("element");
      }

      return _jsp_EmptyTag_6;
    }

    void release()
    {
      if (_jsp_IterateTag_0 != null) {
        _jsp_IterateTag_0.release();
        _jsp_IterateTag_0 = null;
      }
      if (_jsp_DefineTag_1 != null) {
        _jsp_DefineTag_1.release();
        _jsp_DefineTag_1 = null;
      }
      if (_jsp_WriteTag_2 != null) {
        _jsp_WriteTag_2.release();
        _jsp_WriteTag_2 = null;
      }
      if (_jsp_WriteTag_3 != null) {
        _jsp_WriteTag_3.release();
        _jsp_WriteTag_3 = null;
      }
      if (_jsp_NotEmptyTag_4 != null) {
        _jsp_NotEmptyTag_4.release();
        _jsp_NotEmptyTag_4 = null;
      }
      if (_jsp_WriteTag_5 != null) {
        _jsp_WriteTag_5.release();
        _jsp_WriteTag_5 = null;
      }
      if (_jsp_EmptyTag_6 != null) {
        _jsp_EmptyTag_6.release();
        _jsp_EmptyTag_6 = null;
      }
    }
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void caucho_init(ServletConfig config)
  {
    try {
      com.caucho.server.webapp.WebApp webApp
        = (com.caucho.server.webapp.WebApp) config.getServletContext();
      init(config);
      if (com.caucho.jsp.JspManager.getCheckInterval() >= 0)
        _caucho_depends.setCheckInterval(com.caucho.jsp.JspManager.getCheckInterval());
      _jsp_pageManager = webApp.getJspApplicationContext().getPageManager();
      com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
      manager.addTaglibFunctions(_jsp_functionMap, "bean", "/WEB-INF/struts-bean");
      manager.addTaglibFunctions(_jsp_functionMap, "logic", "/WEB-INF/struts-logic");
      com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.InitPageContextImpl(webApp, this);
    } catch (Exception e) {
      throw com.caucho.config.ConfigException.create(e);
    }
  }

  private final static char []_jsp_string28;
  private final static char []_jsp_string4;
  private final static char []_jsp_string26;
  private final static char []_jsp_string31;
  private final static char []_jsp_string1;
  private final static char []_jsp_string25;
  private final static char []_jsp_string9;
  private final static char []_jsp_string20;
  private final static char []_jsp_string11;
  private final static char []_jsp_string14;
  private final static char []_jsp_string12;
  private final static char []_jsp_string3;
  private final static char []_jsp_string10;
  private final static char []_jsp_string8;
  private final static char []_jsp_string16;
  private final static char []_jsp_string6;
  private final static char []_jsp_string18;
  private final static char []_jsp_string7;
  private final static char []_jsp_string15;
  private final static char []_jsp_string19;
  private final static char []_jsp_string13;
  private final static char []_jsp_string24;
  private final static char []_jsp_string17;
  private final static char []_jsp_string29;
  private final static char []_jsp_string5;
  private final static char []_jsp_string32;
  private final static char []_jsp_string2;
  private final static char []_jsp_string33;
  private final static char []_jsp_string30;
  private final static char []_jsp_string22;
  private final static char []_jsp_string21;
  private final static char []_jsp_string27;
  private final static char []_jsp_string23;
  private final static char []_jsp_string0;
  static {
    _jsp_string28 = "')\" style=\"color:#0000FF\">\u4e0b\u8f7d</a>\r\n							".toCharArray();
    _jsp_string4 = "/public/My97DatePicker/WdatePicker.js\"></script>\r\n	</head>\r\n	<script language=\"javascript\">\r\nfunction finds(){\r\n    var st = new Date(frmGo.startTime.value.replace(/-/g,'/'));\r\n	var et = new Date(frmGo.endTime.value.replace(/-/g,'/'));\r\n	if(Date.parse(st) - Date.parse(et)>0){\r\n		alert(\"\u5f00\u59cb\u65f6\u95f4\u4e0d\u80fd\u5927\u4e8e\u7ed3\u675f\u65f6\u95f4!\");\r\n		return false;\r\n	}\r\n	   frmGo.submit();\r\n}\r\nfunction c(){\r\n    document.all.startTime.value=\"\";\r\n    document.all.endTime.value=\"\";\r\n    document.all.user.value=\"\";   \r\n    document.getElementById(\"belongProject\").options[0].selected=true;\r\n} \r\nfunction onView(download){\r\n	if(download.length == 0){\r\n		alert(\"\u6ca1\u6709\u5934\u50cf\u6587\u4ef6\uff0c\u65e0\u6cd5\u4e0b\u8f7d\uff01\");\r\n		return false;\r\n	}\r\n	frmGo.action=\"doAppUserInfo.do?method=downloadApk&download=\"+download;\r\n   	frmGo.submit();\r\n}\r\n</script>\r\n	<body>\r\n		<span class=\"title_1\"></span>\r\n		<form name=\"frmGo\" method=\"post\" action=\"doAppUserInfo.do?method=queryAppUserInfo\">			\r\n			".toCharArray();
    _jsp_string26 = "\r\n						</td>\r\n						<td>".toCharArray();
    _jsp_string31 = "</td>						 						\r\n					</tr>\r\n				".toCharArray();
    _jsp_string1 = "\r\n\r\n<html>\r\n	<head>\r\n		<meta http-equiv=\"Content-Type\" content=\"text/html; charset=gb2312\">\r\n		<title>\u65e0\u6807\u9898\u6587\u6863</title>\r\n		<link href=\"".toCharArray();
    _jsp_string25 = "\r\n							".toCharArray();
    _jsp_string9 = "\r\n                 <tr class=\"title_3\">\r\n                       <td colspan=\"15\">\r\n					  \u6ce8\u518c\u65f6\u95f4\r\n                     <input name=\"startTime\" type=\"text\" class=\"txt_1\"  id=\"startTime\" style=\"cursor:text\"\r\n								value=\"".toCharArray();
    _jsp_string20 = "\r\n					<tr class=\"tr_5\" onmouseover='this.className=\"tr_4\"' onmouseout='this.className=\"tr_5\"' >\r\n						<td>".toCharArray();
    _jsp_string11 = "\" onclick=\"WdatePicker()\"\r\n								size=\"9\" readonly>						\r\n						\u624b\u673a\u53f7				\r\n						    <input id=\"user\" name=\"user\" type=\"text\" class=\"txt_1\" \r\n						    value=\"".toCharArray();
    _jsp_string14 = "\r\n									".toCharArray();
    _jsp_string12 = "\" size=\"9\">\r\n						\u9879\u76ee\r\n							".toCharArray();
    _jsp_string3 = "/public/public.js\"></script>   <!-- \u8c03\u7528\u6b64\u65b9\u6cd5 -->\r\n		<script language=\"JavaScript\"\r\n			src=\"".toCharArray();
    _jsp_string10 = "\" onclick=\"WdatePicker()\"\r\n								size=\"9\" readonly> -\r\n							<input name=\"endTime\" type=\"text\" class=\"txt_1\" id=\"endTime\" style=\"cursor:text\"\r\n								value=\"".toCharArray();
    _jsp_string8 = "\r\n		\r\n			<table width=\"100%\" class=\"table\" border=0 cellpadding=\"0\" cellspacing=\"1\">\r\n               <tr>\r\n                <th colspan=\"15\" nowrap=\"nowrap\" align=\"left\">\r\n                    APP\u7528\u6237\u4fe1\u606f\r\n                </th>\r\n                </tr>\r\n                ".toCharArray();
    _jsp_string16 = "' ".toCharArray();
    _jsp_string6 = "</strong>\r\n			               <input type=\"hidden\" name=\"user_id\" value=\"".toCharArray();
    _jsp_string18 = "\r\n							</select>\r\n						<input name=\"find1\" type=\"button\" class=\"but_1\" accesskey=\"f\"\r\n							tabindex=\"f\" value=\"\u641c \u7d22\" onclick=\"javascript:finds()\">\r\n					     <input name=\"clear\" type=\"button\" class=\"but_1\" accesskey=\"c\"\r\n						    tabindex=\"c\"  value=\"\u6e05\u9664\u641c\u7d22\" onclick=\"c()\">\r\n				</tr> \r\n				".toCharArray();
    _jsp_string7 = "\"/>\r\n			            </font>\r\n			     </td>\r\n			   </tr>\r\n			</table>\r\n		 ".toCharArray();
    _jsp_string15 = "																	\r\n									<option value='".toCharArray();
    _jsp_string19 = "\r\n                  <tr class=\"title_2\"> \r\n                  	<td width=\"9%\" >\u6ce8\u518c\u65f6\u95f4</td>\r\n                  	<td width=\"5%\">\u7528\u6237ID</td>  \r\n                  	<td width=\"6%\" >\u9879\u76ee</td>  \r\n                  	<td width=\"8%\" >\u624b\u673a\u53f7</td> \r\n                  	<td width=\"6%\" >\u6635\u79f0</td>\r\n                  	<td width=\"5%\" >\u7ed1\u5b9a\u8bbe\u5907\u6570</td>\r\n                  	<td width=\"5%\" >\u7ed1\u5b9a\u6b21\u6570</td>\r\n                  	<td width=\"5%\" >\u5206\u4eab\u8bbe\u5907\u6570</td> \r\n                  	<td width=\"8%\" >\u5bc6\u7801</td>\r\n                  	<td width=\"5%\" >\u5934\u50cf</td>                  	\r\n                  	<td width=\"8%\" >\u624b\u673a\u578b\u53f7</td>\r\n                  	<td width=\"8%\" >\u7cfb\u7edf\u7248\u672c</td>\r\n                    <td width=\"8%\" >APP\u7248\u672c</td>\r\n                    <td width=\"8%\" >IP\u5730\u5740</td>\r\n                    <td width=\"8%\" >\u5f52\u5c5e\u5730</td>\r\n				</tr>\r\n \r\n				".toCharArray();
    _jsp_string13 = "\r\n							<select id=\"belongProject\" name=\"belongProject\">\r\n								<option value=\"\">\u5168\u90e8</option>\r\n								".toCharArray();
    _jsp_string24 = "\r\n								".toCharArray();
    _jsp_string17 = "</option>\r\n								".toCharArray();
    _jsp_string29 = "							\r\n						</td>						\r\n						<td>".toCharArray();
    _jsp_string5 = "\r\n			<table class=\"table_1\" style=\"font-size:14px;margin-bottom:5px;\">\r\n			   <tr>  \r\n			     <td>\r\n			                      \u5f53\u524d\u7528\u6237ID:\r\n			              <font color=\"#FFA500\">\r\n			               <strong >".toCharArray();
    _jsp_string32 = " \r\n\r\n			  	<tr class=\"title_3\">\r\n					<td colspan=\"15\" align=\"left\" >  \r\n						".toCharArray();
    _jsp_string2 = "/css/tbls.css\"\r\n			rel=\"stylesheet\" type=\"text/css\">\r\n		<script language=\"JavaScript\"\r\n			src=\"".toCharArray();
    _jsp_string33 = "\r\n					</td>\r\n				</tr>  \r\n			</table>\r\n		</form>\r\n	</body>\r\n</html>".toCharArray();
    _jsp_string30 = "</td>																				\r\n						<td>".toCharArray();
    _jsp_string22 = "</td>	\r\n						<td>".toCharArray();
    _jsp_string21 = "</td>\r\n						<td>".toCharArray();
    _jsp_string27 = "\r\n								<a href=# onclick=\"onView('".toCharArray();
    _jsp_string23 = "</td>\r\n						<td>\r\n							".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n".toCharArray();
  }
}
